````{r fix non unique names}
mapunit.sp<-readOGR(dsn = "M:/geodata/cadastral/plsssection_a_mbr.gdb", layer = "plsssection_a_mbr", encoding="OpenFileGDB")

# Optional fix for 100k quads
slot(mapunit.sp, "data") <- mapunit.sp@data[,c(1:13, 18:19)]

id <- sapply(slot(mapunit.sp, "polygons"), function(x) slot(x, "ID"))
id <- as.numeric(id)
d <- slot(mapunit.sp,"data")

d.sub <- unique(d)
mapunit.sp2 <-mapunit.sp[rownames(d.sub),]

writeOGR(mapunit.sp2, dsn = "M:/geodata/cadastral", layer = "plsssection_a_mbr", driver = "ESRI Shapefile", overwrite_layer = TRUE)
```

```{r create tiles}
# Create tiles (example taken from Hengl getSRTM.R)
tiles <- expand.grid(KEEP.OUT.ATTRS=FALSE, lon=seq(-125,-66,by=1), lat=seq(24,50,by=1))
tiles.points <- tiles
tiles.points$label <- paste(tiles.points$lon, ",", tiles.points$lat, sep="")
coordinates(tiles.points) <- ~ lon+lat
proj4string(tiles.points) <- CRS("+init=epsg:4326")
tiles.poly <- tiles.points
gridded(tiles.poly) <- TRUE
tiles.poly <- rasterToPolygons(raster(tiles.poly, values=T))
tiles.poly@data <- over(tiles.poly, tiles.points, fun=mode)
tiles.poly <- spTransform(tiles.poly, CRS("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))
writePolyShape(tiles.poly["label"], "tilespoly.shp")


# Test script to generate list of tiles
lat <- rep(33:47, 1)
lon <- rep(79:97, 1)

l <- list()
for (i in seq(lat)){
  l[i] <- list(paste("n", lat[i], "w", lon, sep=""))
}
ned <- unlist(l)
```

```{r defintion query}
# Definition query
# Copy Mapunit table out of NASIS 
setwd("C:/Users/stephen.roecker/Documents")
test <- read.csv("test.csv")
mukey <- test$Rec.ID
paste("'", mukey[1:length(mukey)-1], "'",collapse=",", sep="")
# Paste results after the following, "MUKEY" IN ...(    )

```

```{r gdal examples}
gdal_setInstallation(search_path="C:/ProgramData/QGIS/QGISDufour/bin", rescan=T)


ogr2ogr -f "ESRI Shapefile" test.shp test.gdb ca794_a -nln ca794_a

library(raster)
library(rgdal)

ind <- readOGR(dsn="M:/geodata/soils/Region_11_Soils_SSURGO_FY2015/MLRA_11_IND_FY15.gdb", layer="SAPOLYGON", encoding="OpenFileGDB")
ogrInfo("M:/geodata/project_data/11IND/RTSD_Region_11_IND_FY15.gdb", layer="SAPOLYGON")

ogr2ogr(
  src_datasource_name="E:/geodata/project_data/11ATL/11ATL.gdb",
  dst_datasource_name="E:/geodata/project_data/11ATL/cache/11ATL.shp",
  layer="MUPOLYGON",
  where="MUSYM=='362'",
  verbose=TRUE)

test

ogr2ogr -where "MUSYM==362" "E:/geodata/project_data/11ATL/cache/11ATL.shp" "E:/geodata/project_data/11ATL/11ATL.gdb" "MUPOLYGON"

# Subset by SQL query
   ogr2ogr(
      src_datasource_name="M:/geodata/project_data/11GAL/RTSD_Region_11_GAL_FY15.gdb",
      dst_datasource_name="M:/geodata/project_data/11GAL/cache/temp.shp",
      layer="MUPOLYGON",
      where=test,
      s_srs=CRS("+init=epsg:5070"),
      t_srs=CRS("+init=epsg:5070"),
      overwrite=T,
      verbose=TRUE
      )

# Clip polygon using extent
ogr2ogr(
  src_datasource_name="M:/geodata/soils/MLRA_Soil_Survey_Areas_May2014.shp",
  dst_datasource_name="M:/geodata/project_data/11REGION/MLRA_Soil_Survey_Areas_May2014_r11.shp",
  layer="MLRA_Soil_Survey_Areas_May2014",
  t_srs=CRS("+init=epsg:5070"),
  where="NEW_MO IN ('11')",
  verbose=TRUE,
  overwrite=T, 
  progress=T)

bb <- bbox(readOGR(dsn="M:/geodata/project_data/11REGION/MLRA_Soil_Survey_Areas_May2014_r11.shp", layer="MLRA_Soil_Survey_Areas_May2014_r11"))

# Clip shapefile by extent
system(paste('"C:/Program Files/QGIS Dufour/bin/ogr2ogr.exe"', '-overwrite -t_srs EPSG:5070 -clipdst -49675.0230520471 1329474.02694086 1175426.50953029 2591124.11923647 M:/geodata/project_data/11REGION/us_eco_l4_no_r11.shp M:/geodata/ecology/us_eco_l4_no_st.shp'))

system(paste('"C:/Program Files/QGIS Dufour/bin/ogr2ogr.exe"', '-overwrite -t_srs EPSG:5070 -clipdst -49675.0230520471 1329474.02694086 1175426.50953029 2591124.11923647 M:/geodata/project_data/11REGION/geology_a_r11.shp M:/geodata/geology/geology_a_mbr.shp'))

system(paste('"C:/Program Files/QGIS Dufour/bin/ogr2ogr.exe"', '-overwrite -t_srs EPSG:5070 -clipdst -49675.0230520471 1329474.02694086 1175426.50953029 2591124.11923647 M:/geodata/project_data/11REGION/physiography_polygon_r11.shp M:/geodata/geology/physiography_polygon.shp'))

system(paste('"C:/Program Files/QGIS Dufour/bin/ogr2ogr.exe"', '-overwrite -t_srs EPSG:5070 -clipdst -49675.0230520471 1329474.02694086 1175426.50953029 2591124.11923647 M:/geodata/project_data/11REGION/mlra_a_r11.shp M:/geodata/soils/mlra_a_mbr.shp'))

system(paste('"C:/Program Files/QGIS Dufour/bin/ogr2ogr.exe"', '-overwrite -t_srs EPSG:5070 -clipdst -49675.0230520471 1329474.02694086 1175426.50953029 2591124.11923647 M:/geodata/project_data/11REGION/mlra_soil_survey_areas_nov14_r11.shp M:/geodata/soils/MLRA_Soil_Survey_Areas_Nov2014.shp'))
```


```{r maps}
library(maps)
library(sp)
# this may not be necessary, unless I want to use spplot?, simply use
# map package and plot function
state=map("state",plot=FALSE)
p4s=CRS("+proj=longlat +ellps=WGS84")
state.sl=map2SpatialLines(state,proj4string=p4s)
data(us.cities)
names(us.cities)[4:5]=c("y","x")
coordinates(us.cities)<-~x+y
proj4string(us.cities)=p4s

map("state",xlim=c(-87,-74),ylim=c(33,44))
data(world.cities)
map.cities(world.cities,minpop=500000,label=T)
map.axes()

forest=readOGR(dsn="C:/Users/stephen/Documents/Research/Projects/Thesis/Geodata/Overlays/Forest",layer="mnf_proc_bndy_n83_0504")
proj4string(test)
forest=spTransform(forest,CRS("+init=epsg:4326"))
plot(forest,add=T,col="grey")
watershed=readShapePoly("C:/Users/stephen/Documents/Research/Projects/Thesis/Geodata/Covariates/ws16.shp")
proj4string(watershed)=CRS("+init=epsg:26917")
watershed=spTransform(watershed,CRS("+init=epsg:4326"))
plot(watershed,add=T,col="blue")
polygon(c(-81,-81,-80,-80),c(38,39,39,38))

library(maps)
library(maptools)
library(rgdal)

# Extract data from maps package
s <- map('state', fill=T)
test <- map2SpatialPolygons(s, IDs=1:63)
test2 <- SpatialPolygonsDataFrame(test, data.frame(s$names))
proj4string(test2) <- CRS('+proj=longlat +datum=WGS84')
test3 <- spTransform(test2, CRS("+init=epsg:5070"))
writeOGR(dsn=getwd(), test3, 'states4', driver='ESRI Shapefile')

# Expand and insert legend
temp <- spTransform(mupolygon, CRS("+init=epsg:4326"))

test <- data.frame(t(bbox(temp)))
coordinates(test) <- ~x+y

plot(temp, xlim=test$x+c(0, 0.5), ylim=test$y)
map("county", add=T)
map("state",lwd=2,add=T)
map.axes()
legend("right", legend=c("Major rivers", "Reservoirs", "Dams"),
    title="Legend", bty="n",
    lty=c( 1,-1,-1), pch=c(-1,15, 1),
    col=c("dodgerblue3", "darkgreen", "darkred"), bg="antiquewhite1")
```

```{r ratify}
# Dylan's exmaple has the ID column as the MUKEY
# Natively from the file geodatabase gSSURGO is a multi-attribute raster
# Alteration of Dylan's code as follows
library(Hmisc)
library(soilDB)
library(plyr)
library(raster)
setwd("C:/Users/stephen.roecker/Documents")

# load chunk of gSSURGO
r <- raster('MuRaster_90m_clip.tif')
r <- ratify(r)
rat <- levels(r)[[1]]

mu <- read.dbf('MuRaster_90m_clip.tif.vat.dbf',as.is=TRUE)
names(mu)[1] <- 'ID'
mu$MUKEY <- as.integer(mu$MUKEY)

rat.new <- join(rat, mu, by='ID', type='left')
levels(r) <- rat.new
r.mu <- deratify(r, att='MUKEY')

summary(r) ; summary(r.mu)

# Load NASIS report
ecosites<-read.csv("Book1.csv",stringsAsFactors=F)

# Join gSSURGO to NASIS report
names(ecosites)[19]<-"MUKEY"
rat.new<-join(rat,ecosites,by="MUKEY")
levels(test.r) <- rat.new

# convert into standard raster based on new column
r.new <- deratify(test.r, att='Ecosite')

# Write raster
writeRaster(r.new,"test.r.new.tif",format="GTiff",overwrite=T,NAflag=-9999)

```

```{r subset polygon}
mlra <- readOGR(dsn=getwd(), layer="mlra_a_mbr_Dissolve")

id <- sapply(slot(mlra, "polygons"), function(x) slot(x, "ID"))
id <- as.numeric(id)

d <- slot(mlra,"data")
d.sub <- subset(d, MLRARSYM == "30")

plot(mlra[rownames(d.sub),])



test <- readOGR(dsn="I:/geodata/hydrography/NHDH_IN.gdb", layer="NHDWaterbody", encoding="OpenFileGDB")
id <- sapply(slot(mlra, "polygons"), function(x) slot(x, "ID"))
id <- as.numeric(id)

d <- slot(test,"data")
d.sub <- subset(d, Shape_Area > 40489, select=(Shape_Area))

plot(test[rownames(d.sub),])
```


```{r gdal burning}
# Burn Flowline
for(i in seq(nhdgdb)){
  cat(paste(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "burning", nhdgdb[i], "\n"))
  gdal_rasterize(
    src_datasource=nhdgdb[i],
    dst_filename="C:/geodata/project_data/REGION11/nhd30m_fl_warp.tif",
    l="NHDFlowline",
    b=1,
    burn=1,
    verbose=TRUE
  ) 
}


# Burn gSSURGO into NLCD
nlcdpath <- paste(pdpath, office,"/nlcd", 30, "m_11", office, ".tif", sep="")
gssurgopath <- paste(pdpath, office,"/gssurgo", 30, "m_11", office, ".tif", sep="")
for(i in oseq(gssurgopath)){
  r <- raster(nlcdpath[i])
  bb <- bbox(r)
  cat(paste(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "warping", gssurgopath[i], "\n"))
  gdalwarp(
    srcfile=nlcdpath[i],
    dstfile=gssurgopath[i],
    s_srs="EPSG:5070",
    t_srs="EPSG:5070",
    r="near",
    ot="Int32",
    tr=c(30,30),
    te=c(bb[1,1], bb[2,1], bb[1,2], bb[2,2]),
    overwrite=TRUE,
    verbose=TRUE
  )
}

for(i in seq(gssurgopath)){
  cat(paste(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "burning", gssurgopath[i], "\n"))
  gdal_rasterize(
    src_datasource=geodatabase[i],
    dst_filename=gssurgopath[i],
    
    l="MUPOLYGON",
    a="MUKEY",
    verbose=TRUE
  ) 
}
```
